package com.aavn.rs.domain;

// Generated Mar 11, 2015 10:05:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event")
public class Event implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int id;
	private String eventName;
	private Date startDate;
	private String location;
	private Set<Applicant> applicants = new HashSet<Applicant>(0);

	public Event() {
	}

	public Event(int id) {
		this.id = id;
	}

	public Event(int id, String eventName, Date startDate, String location,
			Set<Applicant> applicants) {
		this.id = id;
		this.eventName = eventName;
		this.startDate = startDate;
		this.location = location;
		this.applicants = applicants;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "event_name")
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 29)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "location")
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set<Applicant> getApplicants() {
		return this.applicants;
	}

	public void setApplicants(Set<Applicant> applicants) {
		this.applicants = applicants;
	}

}
